language: scala
scala:
  - 2.10.4
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - vasil.remeniuk@gmail.com
jdk:
  - oraclejdk7
services:
  - elasticsearch
before_script:
  curl https://raw.githubusercontent.com/bokland/rubbercube/master/test/create_test_index.sh | bash